<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ss_get_options {
	public function process(
		$ip, &$stats = array(), &$options = array(), &$post = array()
	) {
// Y/N options
		$options = get_option( 'ss_stop_sp_reg_options' );
// Allow List Y/N options
// not all Y/N options can be changed, but we need them for the load loops
		$defaultWL = array(
			'chkadminlog'      => 'Y',
			'chkaws'           => 'N',
			'chkcloudflare'    => 'Y',
			'chkgcache'        => 'Y',
			'chkgenallowlist'  => 'N',
			'chkgoogle'        => 'Y',
			'chkmiscallowlist' => 'Y',
			'chkpaypal'        => 'Y',
			'chkform'          => 'N',
			'chkscripts'       => 'Y',
			'chkvalidip'       => 'Y',
			'chkwlem'          => 'Y',
			'chkwluserid'      => 'N',
			'chkwlist'         => 'Y',
			'chkyahoomerchant' => 'Y',
			'chkstripe'        => 'Y',
			'chkauthorizenet'  => 'Y',
			'chkbraintree'     => 'Y',
			'chkrecurly'       => 'Y'
		);
// Deny List Y/N settings
		$defaultBL = array(
			'chk404'        => 'Y',
			'chkaccept'     => 'Y',
			'chkadmin'      => 'Y',
			'chkagent'      => 'Y',
			'chkamazon'     => 'N',
			'chkbcache'     => 'Y',
			'chkblem'       => 'Y',
			'chkbluserid'   => 'N',
			'chkblip'       => 'Y',
			'chkbotscout'   => 'Y',
			'chkdisp'       => 'Y',
			'chkdnsbl'      => 'Y',
			'chkexploits'   => 'Y',
			'chkgooglesafe' => 'N',
			'chkhoney'      => 'Y',
			'chkhosting'    => 'Y',
			'chkinvalidip'  => 'Y',
			'chklong'       => 'Y',
			'chkshort'      => 'Y',
			'chkbbcode'     => 'Y',
			'chkreferer'    => 'Y',
			'chksession'    => 'Y',
			'chksfs'        => 'Y',
			'chkspamwords'  => 'Y',
			'chktld'        => 'Y',
			'chkubiquity'   => 'Y',
			'chkakismet'    => 'Y',
			'chkmulti'      => 'Y',
			'chktor'     	=> 'Y',
			'chkperiods'	=> 'N',
			'chkhyphens'	=> 'N'
		);
// control options that can be set - not checks
		$defaultsCTRL   = array(
			'chkemail'            => 'Y',
			'chkip'               => 'Y',
			'chkcomments'         => 'Y',
			'chksignup'           => 'Y',
			'chkxmlrpc'           => 'Y',
			'chkwpmail'           => 'Y',
			'addtoallowlist'      => 'Y',
			'wlreqmail'           => '',
			// email where the request go to
			'wlreq'               => 'Y',
			// using this to see if we display the notify form
			'redir'               => 'N',
			'chkcaptcha'          => 'A',
			'chkxff'              => 'N',
			'notify'              => 'Y',
			'chkspoof'            => 'N',
			'filterregistrations' => 'Y'
			// filter registration attempts - even if not from post
		);
		$defaultARRAY   = array(
			'badagents'  => array(
				"Abonti",
				"aggregator",
				"AhrefsBot",
				"asterias",
				"BDCbot",
				"BLEXBot",
				"BuiltBotTough",
				"Bullseye",
				"BunnySlippers",
				"ca-crawler",
				"CCBot",
				"Cegbfeieh",
				"CheeseBot",
				"CherryPicker",
				"CherryPickerElite",
				"CherryPickerSE",
				"CopyRightCheck",
				"cosmos",
				"Crescent Internet ToolPak",
				"Crescent",
				"discobot",
				"DittoSpyder",
				"DOC",
				"DotBot",
				"Download Ninja",
				"EasouSpider",
				"EmailCollector",
				"EmailSiphon",
				"EmailWolf",
				"EroCrawler",
				"Exabot",
				"ExtractorPro",
				"Fasterfox",
				"FeedBooster",
				"Foobot",
				"Genieo",
				"grub-client",
				"Harvest",
				"hloader",
				"httplib",
				"HTTrack",
				"humanlinks",
				"ieautodiscovery",
				"InfoNaviRobot",
				"IstellaBot",
				"Java/1.",
				"JennyBot",
				"k2spider",
				"Kenjin Spider",
				"Keyword Density/0.9",
				"larbin",
				"LexiBot",
				"libWeb",
				"libwww",
				"LinkextractorPro",
				"linko",
				"LinkScan/8.1a Unix",
				"LinkWalker",
				"LNSpiderguy",
				"lwp-trivial",
				"lwp-trivial",
				"magpie",
				"Mata Hari",
				'MaxPointCrawler',
				'MegaIndex',
				"Microsoft URL Control",
				"MIIxpc",
				"Mippin",
				"Missigua Locator",
				"Mister PiX",
				"MJ12bot",
				"moget",
				"MSIECrawler",
				"NetAnts",
				"NICErsPRO",
				"Niki-Bot",
				"NPBot",
				"Nutch",
				"Offline Explorer",
				"Openfind data gathere",
				"Openfind",
				'panscient.com',
				"PHP/5.{",
				"ProPowerBot/2.14",
				"ProWebWalker",
				"Python-urllib",
				"QueryN Metasearch",
				"RepoMonkey",
				"RepoMonkey",
				"RMA",
				'SemrushBot',
				"SeznamBot ",
				"SISTRIX",
				"sitecheck.Internetseer.com",
				"SiteSnagger",
				"SnapPreviewBot",
				"Sogou",
				"SpankBot",
				"spanner",
				"spbot",
				"Spinn3r",
				"suzuran",
				"Szukacz/1.4",
				"Teleport Pro/1.29",
				"Teleport",
				"TeleportPro",
				"Telesoft",
				"The Intraformant",
				"TheNomad",
				"TightTwatBot",
				"Titan",
				"toCrawl/UrlDispatcher",
				"True_Robot",
				"True_Robot/1.0",
				"turingos",
				"TurnitinBot",
				"UbiCrawler",
				"UnisterBot",
				"URLy Warning",
				"VCI WebViewer VCI WebViewer Win32",
				"VCI",
				"WBSearchBot",
				"Web Downloader/6.9",
				"Web Image Collector",
				"WebAuto",
				"WebBandit",
				"WebBandit/3.50",
				"WebCopier v4.0",
				"WebCopier",
				"WebEnhancer",
				"WebmasterWorldForumBot",
				"WebReaper",
				"WebSauger",
				"Website Quester",
				"Webster Pro",
				"WebStripper",
				"WebZip",
				"Wotbox",
				"wsr-agent",
				"WWW-Collector-E",
				"Xenu",
				"yandex",
				"Zao",
				"Zeus",
				"Zeus",
				"ZyBORG",
				'coccoc',
				'Incutio',
				'lmspider',
				'memoryBot',
				'SemrushBot',
				'serf',
				'Unknown',
				'uptime files'
			),
			'badTLDs'    => array(),
			'blist'      => array(),
			'payoptions' => array(),
			'wlist'      => array(),
			'spamwords'  => array(
				'#1',
				'100% free',
				'100% more',
				'100% satisfied',
				'Accept credit cards',
				'Act now',
				'Ad',
				'Additional income',
				'All new',
				'Apply now',
				'As seen on',
				'Bargain',
				'Be your own boss',
				'Become a member',
				'Beneficiary',
				'Best price',
				'Big bucks',
				'Billing',
				'Billion',
				'Bonus',
				'Bulk email',
				'Buy direct',
				'Call now',
				'Cancel at any time',
				'Cards accepted',
				'Cash',
				'Cash bonus',
				'Cents on the dollar',
				'Certified',
				'Cheap',
				'Check or money order',
				'Claims',
				'Clearance',
				'Click below',
				'Click here',
				'Compare rates',
				'Confidentiality',
				'Congratulations',
				'Consolidate debt',
				'Credit card offers',
				'Cures',
				'Deal',
				'Dear friend',
				'Debt',
				'Direct email',
				'Direct marketing',
				'Discount',
				'Do it today',
				'Don’t delete',
				'Double your cash',
				'Double your income',
				'Earn extra cash',
				'Earn money',
				'Eliminate bad credit',
				'Exclusive deal',
				'Expect to earn',
				'Extra cash',
				'Extra income',
				'Fantastic',
				'Fast cash',
				'Financial freedom',
				'Free access',
				'Free consultation',
				'Free gift',
				'Free hosting',
				'Free info',
				'Free investment',
				'Free membership',
				'Free money',
				'Free preview',
				'Free quote',
				'Free trial',
				'Full refund',
				'Get it now',
				'Get out of debt',
				'Get paid',
				'Get started now',
				'Giveaway',
				'Guaranteed',
				'Hidden charges',
				'Human growth hormone',
				'Important information regarding',
				'In accordance with laws',
				'Income',
				'Increase sales',
				'Increase traffic',
				'Incredible deal',
				'Information you requested',
				'Instant',
				'Internet marketing',
				'Investment',
				'Join millions',
				'Lifetime',
				'Limited time',
				'Loans',
				'Lose weight',
				'Lower rates',
				'Lowest price',
				'Luxury',
				'Make money',
				'Marketing solution',
				'Mass email',
				'Meet singles',
				'Message contains',
				'Million dollars',
				'Miracle',
				'Money back',
				'Mortgage rates',
				'Multi-level marketing',
				'Name brand',
				'New customers only',
				'No catch',
				'No cost',
				'No credit check',
				'No fees',
				'No gimmick',
				'No hidden costs',
				'No hidden fees',
				'No interest',
				'No investment',
				'No obligation',
				'No purchase necessary',
				'No questions asked',
				'No strings attached',
				'Not junk',
				'Notspam',
				'Obligation',
				'Offer',
				'Once in a lifetime',
				'One time',
				'Online marketing',
				'Opt in',
				'Order now',
				'Passwords',
				'Pennies a day',
				'Please read',
				'Potential earnings',
				'Pre-approved',
				'Prize',
				'Promise',
				'Pure profit',
				'Quote',
				'Rates',
				'Refinance',
				'Removal',
				'Requires initial investment',
				'Reserves the right',
				'Risk-free',
				'Satisfaction guaranteed',
				'Save big money',
				'Save up to',
				'Score',
				'Search engine',
				'See for yourself',
				'Sent in compliance',
				'Sign up free',
				'Social security number',
				'Special promotion',
				'Subject to…',
				'Take action',
				'Terms and conditions',
				'This isn’t a scam',
				'This isn’t junk',
				'This isn’t spam',
				'This won’t last',
				'Trial',
				'Undisclosed',
				'Unlimited',
				'Unsecured credit',
				'Unsecured debt',
				'Unsolicited',
				'Urgent',
				'Valium',
				'Viagra',
				'Vicodin',
				'Warranty',
				'We hate spam',
				'Web traffic',
				'Weight loss',
				'What are you waiting for?',
				'While supplies last',
				'Will not believe your eyes',
				'Winner',
				'Winning',
				'Work from home',
				'Xanax',
				'You are a winner',
				'You have been selected',
				'$$$',
				'4u',
				'4-u',
				'Additional income',
				'additional-income',
				'adipex',
				'advicer',
				'air max',
				'allstate',
				'ambien',
				'baccarrat',
				'BackPage Ads Posting',
				'BackPage Posting',
				'barbour northumbria',
				'Be your own boss',
				'Beneficiary',
				'bingo',
				'blackjack',
				'blackjack',
				'bllogspot',
				'booker',
				'Buy direct',
				'byob',
				'carisoprodol',
				'car-rental-e-site',
				'car-rentals-e-site',
				'Cash bonus',
				'casino',
				'chatroom',
				'Check or money order',
				'cialis',
				'Collect your prize',
				'coolhu',
				'CraigsList Ads Posting',
				'credit-card-debt',
				'credit-report',
				'Cures baldness',
				'cwas',
				'cyclen',
				'cyclobenzaprine',
				'dating-e-site',
				'day-trading',
				'Dear Friend',
				'debt-consolidation',
				'debt-consolidation',
				'Direct marketing',
				'discreetordering',
				'Double your income',
				'dutyfree',
				'duty-free',
				'Earn extra cash',
				'Easy date',
				'Email harvest',
				'email-marketing',
				'equityloans',
				'Extra income',
				'extra-income',
				'fast-cash',
				'Financial Schemes',
				'fioricet',
				'flowers-leading-site',
				'Free gift card',
				'freenet',
				'freenet-shopping',
				'gambling-',
				'hair-loss',
				'health-insurancedeals',
				'holdem',
				'Home based',
				'Home based business',
				'home security systems',
				'homebased',
				'home-based',
				'homeequityloans',
				'homefinance',
				'Hot men',
				'Hot women',
				'hotel-dealse-site',
				'hotele-site',
				'hotelse-site',
				'incest',
				'Income from home',
				'Increase sales',
				'Increase traffic',
				'insurancedeals',
				'insurance-quotes',
				'insurnce',
				'Internet marketing',
				'jrcreations',
				'Lead generation',
				'levitra',
				'Lose weight',
				'macinstruct',
				'Make $',
				'Make money',
				'Marketing solutions',
				'Meet singles',
				'Million dollars',
				'Month trial offer',
				'Mortgage',
				'mortgagequotes',
				'nike',
				'One hundred percent free',
				'-online',
				'Online biz opportunity',
				'Online degree',
				'Online pharmacy',
				'onlinegambling',
				'online-gambling',
				'Opportunity',
				'ottawavalleyag',
				'ownsthis',
				'paxil',
				'penis',
				'Perform in bed',
				'pharmacy',
				'phentermine',
				'poker',
				'poker-chip',
				'Potential earnings',
				'poze',
				'pussy',
				'real money',
				'Refinance',
				'Removes wrinkles',
				'rental-car-e-site',
				'Reverses aging',
				'ringtones',
				'roulette',
				'Save big money',
				'Score tonight',
				'Search Engine Optimization',
				'seo-',
				'shemale',
				'Shox',
				'sibutramine',
				'Sign-up free today',
				'slot-machine',
				'Social Security Number',
				'Stock alert',
				'Stop snoring',
				'thorcarlson',
				'top-e-site',
				'top-site',
				'tramadol',
				'trim-spa',
				'ultram',
				'University diplomas',
				'Unsecured debt',
				'Urgent proposal',
				'valeofglamorganconservatives',
				'viagra',
				'Viagra',
				'vioxx',
				'Web traffic',
				'weightloss',
				'weight-loss',
				'Work from home',
				'workathome',
				'work-at-home',
				'xanax',
				'You’re a winner',
				'zolus'

			)
		);
		$defaultSVC     = array(
			'apikey'                 => '',
			'honeyapi'               => '',
			'botscoutapi'            => '',
			'googleapi'              => '',
			'recaptchaapisecret'     => '',
			'recaptchaapisite'       => '',
			'solvmediaapivchallenge' => '',
			'solvmediaapiverify'     => '',
			'blogseyekey'            => '',
			'sesstime'               => 4,
			'sfsfreq'                => 0,
			'hnyage'                 => 9999,
			'botfreq'                => 0,
			'sfsage'                 => 9999,
			'hnylevel'               => 5,
			'botage'                 => 9999,
			'multicnt'               => 5,
			'multitime'              => 3
		);
		$force          = true;
		$defaults       = array(
			'version'        => SS_VERSION,
			'ss_sp_cache'    => 25,
			'ss_sp_hist'     => 25,
			'ss_sp_good'     => 2,
			'ss_sp_cache_em' => 4,
			'redirurl'       => '',
			'logfilesize'    => 0,
			'rejectmessage'  => "Access Denied<br />"
		);
		$defaultCOUNTRY = array( // all yes - changed to no
			'chkAD' => 'N',
			'chkAE' => 'N',
			'chkAF' => 'N',
			'chkAL' => 'N',
			'chkAM' => 'N',
			'chkAR' => 'N',
			'chkAT' => 'N',
			'chkAU' => 'N',
			'chkAX' => 'N',
			'chkAZ' => 'N',
			'chkBA' => 'N',
			'chkBB' => 'N',
			'chkBD' => 'N',
			'chkBE' => 'N',
			'chkBG' => 'N',
			'chkBH' => 'N',
			'chkBN' => 'N',
			'chkBO' => 'N',
			'chkBR' => 'N',
			'chkBS' => 'N',
			'chkBY' => 'N',
			'chkBZ' => 'N',
			'chkCA' => 'N',
			'chkCD' => 'N',
			'chkCH' => 'N',
			'chkCL' => 'N',
			'chkCN' => 'N',
			'chkCO' => 'N',
			'chkCR' => 'N',
			'chkCU' => 'N',
			'chkCW' => 'N',
			'chkCY' => 'N',
			'chkCZ' => 'N',
			'chkDE' => 'N',
			'chkDK' => 'N',
			'chkDO' => 'N',
			'chkDZ' => 'N',
			'chkEC' => 'N',
			'chkEE' => 'N',
			'chkES' => 'N',
			'chkEU' => 'N',
			'chkFI' => 'N',
			'chkFJ' => 'N',
			'chkFR' => 'N',
			'chkGB' => 'N',
			'chkGE' => 'N',
			'chkGF' => 'N',
			'chkGI' => 'N',
			'chkGP' => 'N',
			'chkGR' => 'N',
			'chkGT' => 'N',
			'chkGU' => 'N',
			'chkGY' => 'N',
			'chkHK' => 'N',
			'chkHN' => 'N',
			'chkHR' => 'N',
			'chkHT' => 'N',
			'chkHU' => 'N',
			'chkID' => 'N',
			'chkIE' => 'N',
			'chkIL' => 'N',
			'chkIN' => 'N',
			'chkIQ' => 'N',
			'chkIR' => 'N',
			'chkIS' => 'N',
			'chkIT' => 'N',
			'chkJM' => 'N',
			'chkJO' => 'N',
			'chkJP' => 'N',
			'chkKE' => 'N',
			'chkKG' => 'N',
			'chkKH' => 'N',
			'chkKR' => 'N',
			'chkKW' => 'N',
			'chkKY' => 'N',
			'chkKZ' => 'N',
			'chkLA' => 'N',
			'chkLB' => 'N',
			'chkLK' => 'N',
			'chkLT' => 'N',
			'chkLU' => 'N',
			'chkLV' => 'N',
			'chkMD' => 'N',
			'chkME' => 'N',
			'chkMK' => 'N',
			'chkMM' => 'N',
			'chkMN' => 'N',
			'chkMO' => 'N',
			'chkMP' => 'N',
			'chkMQ' => 'N',
			'chkMT' => 'N',
			'chkMV' => 'N',
			'chkMX' => 'N',
			'chkMY' => 'N',
			'chkNC' => 'N',
			'chkNI' => 'N',
			'chkNL' => 'N',
			'chkNO' => 'N',
			'chkNP' => 'N',
			'chkNZ' => 'N',
			'chkOM' => 'N',
			'chkPA' => 'N',
			'chkPE' => 'N',
			'chkPG' => 'N',
			'chkPH' => 'N',
			'chkPK' => 'N',
			'chkPL' => 'N',
			'chkPR' => 'N',
			'chkPS' => 'N',
			'chkPT' => 'N',
			'chkPW' => 'N',
			'chkPY' => 'N',
			'chkQA' => 'N',
			'chkRO' => 'N',
			'chkRS' => 'N',
			'chkRU' => 'N',
			'chkSA' => 'N',
			'chkSC' => 'N',
			'chkSE' => 'N',
			'chkSG' => 'N',
			'chkSI' => 'N',
			'chkSK' => 'N',
			'chkSV' => 'N',
			'chkSX' => 'N',
			'chkSY' => 'N',
			'chkTH' => 'N',
			'chkTJ' => 'N',
			'chkTM' => 'N',
			'chkTR' => 'N',
			'chkTT' => 'N',
			'chkTW' => 'N',
			'chkUA' => 'N',
			'chkUK' => 'N',
			'chkUS' => 'N',
			'chkUY' => 'N',
			'chkUZ' => 'N',
			'chkVC' => 'N',
			'chkVE' => 'N',
			'chkVN' => 'N',
			'chkYE' => 'N'
		);
		$ansa = array_merge( $defaultWL, $defaultsCTRL, $defaultBL,
			$defaultARRAY, $defaultSVC, $defaultCOUNTRY, $defaults );
// to keep from getting option creep we then set the options from opts back into the ansa
// had to do this to get rid of obsolete or mistaken options
		if ( empty( $options ) || ! is_array( $options ) ) {
			$options = array();
		}
		foreach ( $options as $key => $val ) {
			if ( array_key_exists( $key, $ansa ) ) {
				$ansa[ $key ] = $options[ $key ];
			} else {
// sfs_debug_msg("option $key missing from $options");
			}
		}
		$ansa['version'] = SS_VERSION;
// check the numeric varables for numericness - user can enter anything
		if ( ! is_numeric( $ansa['botage'] ) ) {
			$ansa['botage'] = 9999;
		}
		if ( ! is_numeric( $ansa['botfreq'] ) ) {
			$ansa['botfreq'] = 0;
		}
		if ( ! is_numeric( $ansa['hnyage'] ) ) {
			$ansa['hnyage'] = 9999;
		}
		if ( ! is_numeric( $ansa['hnylevel'] ) ) {
			$ansa['hnylevel'] = 5;
		}
		if ( ! is_numeric( $ansa['ss_sp_cache'] ) ) {
			$ansa['ss_sp_cache'] = 25;
		}
		if ( ! is_numeric( $ansa['ss_sp_cache_em'] ) ) {
			$ansa['ss_sp_cache_em'] = 10;
		}
		if ( ! is_numeric( $ansa['ss_sp_good'] ) ) {
			$ansa['ss_sp_good'] = 2;
		}
		if ( ! is_numeric( $ansa['ss_sp_hist'] ) ) {
			$ansa['ss_sp_hist'] = 25;
		}
		if ( ! is_numeric( $ansa['sesstime'] ) ) {
			$ansa['sesstime'] = 4;
		}
		if ( ! is_numeric( $ansa['sfsage'] ) ) {
			$ansa['sfsage'] = 9999;
		}
		if ( ! is_numeric( $ansa['sfsfreq'] ) ) {
			$ansa['sfsfreq'] = 0;
		}
		if ( ! is_numeric( $ansa['ss_sp_good'] ) ) {
			$ansa['ss_sp_good'] = 0;
		}
		if ( ! is_numeric( trim( $ansa['logfilesize'] ) ) ) {
			$ansa['logfilesize'] = 0;
		}
		$ansa['chkcloudflare'] = 'Y'; // force it true for now
		ss_set_options( $ansa ); // new version, need to set the new options
// sfs_debug_msg( "in get options\r\n".print_r( $ansa, true ) );		
		return $ansa;
	}
}
?>